---
version: '2'
services:
  exchange:
    command: ["bundle", "exec", "rails", "db:setup", "&&", "bundle", "exec", "puma", "-C", "config/puma.config"]
    environment:
      - DATABASE_HOST=exchange-db
      - DATABASE_USER=postgres
      - REDIS_URL=redis://exchange-redis
      - RAILS_ENV=development
      - PGDATA=/tmp
    env_file: ../.env
    extends:
      file: build.yml
      service: exchange
    ports:
      - 8080:8080
    volumes:
      - ../:/app
    depends_on:
      - exchange-db
  exchange-db:
    image: postgres:9.6-alpine
  exchange-redis:
    image: redis:3.2-alpine
  worker:
    extends:
      file: build.yml
      service: exchange
    environment:
      - DATABASE_HOST=exchange-db
      - DATABASE_USER=postgres
      - REDIS_URL=redis://exchange-redis
      - RAILS_ENV=development
      - PGDATA=/tmp
    env_file: ../.env
    command: bundle exec sidekiq
    depends_on:
      - exchange-db
