# This is an autogenerated file for dynamic methods in Fulfillment
# Please rerun rake rails_rbi:models to regenerate.
# typed: strong

class Fulfillment::Relation < ActiveRecord::Relation
  include Fulfillment::NamedScope
  extend T::Generic
  Elem = type_member(fixed: Fulfillment)
end

class Fulfillment < ApplicationRecord
  extend T::Sig
  extend T::Generic
  extend Fulfillment::NamedScope
  Elem = type_template(fixed: Fulfillment)

  sig { returns(T.nilable(String)) }
  def courier(); end

  sig { params(value: T.nilable(String)).void }
  def courier=(value); end

  sig { returns(DateTime) }
  def created_at(); end

  sig { params(value: DateTime).void }
  def created_at=(value); end

  sig { returns(T.nilable(Date)) }
  def estimated_delivery(); end

  sig { params(value: T.nilable(Date)).void }
  def estimated_delivery=(value); end

  sig { returns(T.untyped) }
  def id(); end

  sig { params(value: T.untyped).void }
  def id=(value); end

  sig { returns(LineItemFulfillment::Relation) }
  def line_item_fulfillments(); end

  sig { params(value: T.any(T::Array[LineItemFulfillment], LineItemFulfillment::Relation)).void }
  def line_item_fulfillments=(value); end

  sig { returns(LineItem::Relation) }
  def line_items(); end

  sig { params(value: T.any(T::Array[LineItem], LineItem::Relation)).void }
  def line_items=(value); end

  sig { returns(T.nilable(String)) }
  def notes(); end

  sig { params(value: T.nilable(String)).void }
  def notes=(value); end

  sig { returns(T.nilable(String)) }
  def tracking_id(); end

  sig { params(value: T.nilable(String)).void }
  def tracking_id=(value); end

  sig { returns(DateTime) }
  def updated_at(); end

  sig { params(value: DateTime).void }
  def updated_at=(value); end

  sig { returns(PaperTrail::FulfillmentVersion::Relation) }
  def versions(); end

  sig { params(value: T.any(T::Array[PaperTrail::FulfillmentVersion], PaperTrail::FulfillmentVersion::Relation)).void }
  def versions=(value); end

end


module Fulfillment::NamedScope
  extend T::Sig

  sig { returns(Fulfillment::Relation) }
  def all(); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Fulfillment::Relation) }
  def select(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Fulfillment::Relation) }
  def order(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Fulfillment::Relation) }
  def reorder(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Fulfillment::Relation) }
  def group(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Fulfillment::Relation) }
  def limit(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Fulfillment::Relation) }
  def offset(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Fulfillment::Relation) }
  def joins(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Fulfillment::Relation) }
  def left_joins(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Fulfillment::Relation) }
  def left_outer_joins(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Fulfillment::Relation) }
  def where(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Fulfillment::Relation) }
  def rewhere(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Fulfillment::Relation) }
  def preload(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Fulfillment::Relation) }
  def eager_load(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Fulfillment::Relation) }
  def includes(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Fulfillment::Relation) }
  def from(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Fulfillment::Relation) }
  def lock(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Fulfillment::Relation) }
  def readonly(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Fulfillment::Relation) }
  def extending(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Fulfillment::Relation) }
  def or(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Fulfillment::Relation) }
  def having(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Fulfillment::Relation) }
  def create_with(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Fulfillment::Relation) }
  def distinct(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Fulfillment::Relation) }
  def references(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Fulfillment::Relation) }
  def none(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Fulfillment::Relation) }
  def unscope(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Fulfillment::Relation) }
  def merge(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Fulfillment::Relation) }
  def except(*args, block); end

end

