# This is an autogenerated file for dynamic methods in LineItemFulfillment
# Please rerun rake rails_rbi:models to regenerate.
# typed: strong

class LineItemFulfillment::Relation < ActiveRecord::Relation
  include LineItemFulfillment::NamedScope
  extend T::Generic
  Elem = type_member(fixed: LineItemFulfillment)
end

class LineItemFulfillment < ApplicationRecord
  extend T::Sig
  extend T::Generic
  extend LineItemFulfillment::NamedScope
  Elem = type_template(fixed: LineItemFulfillment)

  sig { returns(DateTime) }
  def created_at(); end

  sig { params(value: DateTime).void }
  def created_at=(value); end

  sig { returns(T.nilable(Fulfillment)) }
  def fulfillment(); end

  sig { params(value: T.nilable(Fulfillment)).void }
  def fulfillment=(value); end

  sig { returns(T.nilable(T.untyped)) }
  def fulfillment_id(); end

  sig { params(value: T.nilable(T.untyped)).void }
  def fulfillment_id=(value); end

  sig { returns(T.untyped) }
  def id(); end

  sig { params(value: T.untyped).void }
  def id=(value); end

  sig { returns(T.nilable(LineItem)) }
  def line_item(); end

  sig { params(value: T.nilable(LineItem)).void }
  def line_item=(value); end

  sig { returns(T.nilable(T.untyped)) }
  def line_item_id(); end

  sig { params(value: T.nilable(T.untyped)).void }
  def line_item_id=(value); end

  sig { returns(DateTime) }
  def updated_at(); end

  sig { params(value: DateTime).void }
  def updated_at=(value); end

end


module LineItemFulfillment::NamedScope
  extend T::Sig

  sig { returns(LineItemFulfillment::Relation) }
  def all(); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(LineItemFulfillment::Relation) }
  def select(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(LineItemFulfillment::Relation) }
  def order(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(LineItemFulfillment::Relation) }
  def reorder(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(LineItemFulfillment::Relation) }
  def group(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(LineItemFulfillment::Relation) }
  def limit(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(LineItemFulfillment::Relation) }
  def offset(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(LineItemFulfillment::Relation) }
  def joins(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(LineItemFulfillment::Relation) }
  def left_joins(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(LineItemFulfillment::Relation) }
  def left_outer_joins(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(LineItemFulfillment::Relation) }
  def where(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(LineItemFulfillment::Relation) }
  def rewhere(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(LineItemFulfillment::Relation) }
  def preload(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(LineItemFulfillment::Relation) }
  def eager_load(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(LineItemFulfillment::Relation) }
  def includes(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(LineItemFulfillment::Relation) }
  def from(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(LineItemFulfillment::Relation) }
  def lock(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(LineItemFulfillment::Relation) }
  def readonly(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(LineItemFulfillment::Relation) }
  def extending(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(LineItemFulfillment::Relation) }
  def or(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(LineItemFulfillment::Relation) }
  def having(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(LineItemFulfillment::Relation) }
  def create_with(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(LineItemFulfillment::Relation) }
  def distinct(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(LineItemFulfillment::Relation) }
  def references(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(LineItemFulfillment::Relation) }
  def none(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(LineItemFulfillment::Relation) }
  def unscope(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(LineItemFulfillment::Relation) }
  def merge(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(LineItemFulfillment::Relation) }
  def except(*args, block); end

end

